git:
  depth: false
  clone: false
branches:
  only:
    - master
    - travis-ci
language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - "$HOME/.m2"

before_install:
  - echo 'github.com ssh-rsa $PUBLIC_KEY' >> ~/.ssh/known_hosts
  - git clone "https://github.com/onsense/universe.git" .
  - git remote set-url origin "https://${GITHUB}@github.com/onsense/universe.git" > /dev/null 2>&1
  - git fetch --force origin "$TRAVIS_BRANCH:remotes/origin/$TRAVIS_BRANCH"
  - git reset --hard "HEAD"
  - git checkout -q -B "$TRAVIS_BRANCH"
  - git config --global gc.auto 0 || true
  - git config user.name "$COMMIT_AUTHOR_NAME"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - ls -la
  - openssl version -a
  - export COMMIT_MESSAGE=`git log -1 --oneline`
#  - openssl aes-256-cbc -K $encrypted_7525ba04b569_key -iv $encrypted_7525ba04b569_iv
#    -in deploy_key.enc -out deploy_key -d
#  - ssh-add ./deploy_key

script:
- mvn clean install -DskipTests=true

deploy:
  provider: script
  script: chmod +x ./configure-maven.sh && ./configure-maven.sh && chmod -x ./configure-maven.sh
    && mvn --settings .mvn/conf/settings.xml --batch-mode --activate-profiles release
    --fail-at-end org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare -DskipTests=true
    -DskipITs=true -Darguments="-DskipTests=true -DskipITs=true"
  skip_cleanup: true
  on:
    all_branches: true